### ISSUE TITLE
Autoreply mail enabled -> unknown user

### ISSUE THREAD

**Issue by NEXSim** [virtualmin/virtualmin-install#86] opened 2023-02-10 15:46 UTC
Hi,

I see a problem since recent versions of Virtualmin installation.

There has been a change since November 25, 2022 which means that on my recent servers installed since January 19, 2023, I have the same problem on all these servers.

When I create an email user, I can send and receive emails. This works fine.

When I enable the autoreply reply, the absence message is sent but I don't receive the email. 
The sender receives a "Mail Delivery System" with the following content:

_This is the mail system at host [serveur1.bild.fr](http://serveur1.bild.fr/).

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<[david-serveur1.bild.fr@vmi1173192.contaboserver.net](mailto:david-serveur1.bild.fr@vmi1173192.contaboserver.net)> (expanded from
    <[david@serveur1.bild.fr](mailto:david@serveur1.bild.fr)>): unknown user: "[david-serveur1.bild.fr](http://david-serveur1.bild.fr/)"_

When i see the mail aliases, i find this entry...

Alias from.. | Alias to..
david-serveur1.bild.fr | Address \david-serveur1.bild.fr
Program /etc/webmin/virtual-server/autoreply.pl /home/serveur1/autoreply-david@serveur1.bild.fr.txt david@serveur1.bild.fr /var/virtualmin-autoreply/167604320857804-autoreply-david@serveur1.bild.fr.txt

Then i don't how to resolve that...

If you want, i can send to you the server codes to show the problem.

Thank you so much, 
David MELIS
Nex Studio

**Comment by jcameron** [comment] 2023-02-11 03:00
Does a user with login `david-serveur1.bild.fr` exist in your `/etc/passwd` file? Or a similar one like `david@serveur1.bild.fr` ?

**Comment by NEXSim** [comment] 2023-02-13 07:19
Hi,

Yes, i look a line with ***@***.*** in /etc/passwd

I managed to get it to work properly by taking an older installer from July
2022.
Now I no longer get an error message when the answering machine is
activated.

Bien cordialement,

David MELIS
Développeur Full Stack / Chef de projets
Tél. 03.85.93.68.40
INFRASTRUCTURE RÉSEAUX - SÉCURITÉ INFORMATIQUE
MATÉRIEL INFORMATIQUE - DÉVELOPPEMENT / SITES WEB
<http://www.nex-informatique.com/>*www.nex-informatique.com
<http://www.nex-informatique.com>*
Merci de toujours citer mes messages dans vos réponses.


Le sam. 11 févr. 2023 à 04:00, Jamie Cameron ***@***.***> a
écrit :

**Comment by jcameron** [comment] 2023-02-14 04:17
What do you mean by an older installer?

**Comment by NEXSim** [comment] 2023-02-14 08:51
I take this file installer (attachment) and not the file installer at this
URL link :

http://software.virtualmin.com/gpl/scripts/install.sh

Bien cordialement,

David MELIS
Développeur Full Stack / Chef de projets
Tél. 03.85.93.68.40
INFRASTRUCTURE RÉSEAUX - SÉCURITÉ INFORMATIQUE
MATÉRIEL INFORMATIQUE - DÉVELOPPEMENT / SITES WEB
<http://www.nex-informatique.com/>*www.nex-informatique.com
<http://www.nex-informatique.com>*
Merci de toujours citer mes messages dans vos réponses.


Le mar. 14 févr. 2023 à 05:17, Jamie Cameron ***@***.***> a
écrit :

**Comment by iliajie** [comment] 2023-02-14 09:28
Odd. Using the older installer cannot have such effect.

**Comment by NEXSim** [comment] 2023-02-14 10:04
And yet I guarantee you that it malfunctions with the new installer and
that it works with the old one with the same server and the same
installation procedure.
I don't know what else to tell you.
Make a test and see it.

Bien cordialement,

David MELIS
Développeur Full Stack / Chef de projets
Tél. 03.85.93.68.40
INFRASTRUCTURE RÉSEAUX - SÉCURITÉ INFORMATIQUE
MATÉRIEL INFORMATIQUE - DÉVELOPPEMENT / SITES WEB
<http://www.nex-informatique.com/>*www.nex-informatique.com
<http://www.nex-informatique.com>*
Merci de toujours citer mes messages dans vos réponses.

**Comment by iliajie** [comment] 2023-02-14 10:46
The only difference in the installer (presumably) which may have an affect on mail is that the new installer disables creation of additional usernames for older Postfix authentication to work.

This can be re-enabled though in Virtualmin Configuration page.

The better solution would be to manually fix to have `user@domain` instead of `user-domain` in usernames.

**Comment by NEXSim** [comment] 2023-02-14 10:54
Alright, and how do you do that exactly?

Bien cordialement,

David MELIS
Développeur Full Stack / Chef de projets
Tél. 03.85.93.68.40
INFRASTRUCTURE RÉSEAUX - SÉCURITÉ INFORMATIQUE
MATÉRIEL INFORMATIQUE - DÉVELOPPEMENT / SITES WEB
<http://www.nex-informatique.com/>*www.nex-informatique.com
<http://www.nex-informatique.com>*
Merci de toujours citer mes messages dans vos réponses.

**Comment by iliajie** [comment] 2023-02-14 13:44
I see the issue now.

@jcameron
> Does a user with login david-serveur1.bild.fr exist in your /etc/passwd file? Or a similar one like david@serveur1.bild.fr ?

Jamie, this seems as a bug on Virtualmin side, because even though Virtualmin is configured to _only_ create usernames with `@` it still creates usernames with `-`, even though `\@` user already exists in Postfix.
 
> Alright, and how do you do that exactly?

Sorry about that. Have a look at `/etc/aliases` and `/etc/postfix/virtual` files.

Please remember to run `/usr/sbin/postalias /etc/aliases` and `/usr/sbin/postmap -c /etc/postfix hash:/etc/postfix/virtual` after editing those files.

**Comment by jcameron** [comment] 2023-02-15 02:30
Ok I see the bug that causes this now! It will be fixed in the next release ...

**Closed by jcameron** 2023-02-15 02:30 UTC
Labels: bug

**Comment by NEXSim** [comment] 2023-02-15 06:58
Thank you so much !

Bien cordialement,

David MELIS
Développeur Full Stack / Chef de projets
Tél. 03.85.93.68.40
INFRASTRUCTURE RÉSEAUX - SÉCURITÉ INFORMATIQUE
MATÉRIEL INFORMATIQUE - DÉVELOPPEMENT / SITES WEB
<http://www.nex-informatique.com/>*www.nex-informatique.com
<http://www.nex-informatique.com>*
Merci de toujours citer mes messages dans vos réponses.


Le mer. 15 févr. 2023 à 03:30, Jamie Cameron ***@***.***> a
écrit :

**Comment by jcameron** [comment] 2023-02-16 18:59
It could be a while, but you can apply this patch to get the fix now : https://github.com/virtualmin/virtualmin-gpl/commit/fcd7ed451a4a5c7afa893f166b8634b4bac30c2f

**Comment by NEXSim** [comment] 2023-02-17 08:43
Hi,

I have applied this patch and i see the bug again.

I have restarted the webmin service to confirm.

Do you want the root access to verify ?

Thank you.

Bien cordialement,

David MELIS
Développeur Full Stack / Chef de projets
Tél. 03.85.93.68.40
INFRASTRUCTURE RÉSEAUX - SÉCURITÉ INFORMATIQUE
MATÉRIEL INFORMATIQUE - DÉVELOPPEMENT / SITES WEB
<http://www.nex-informatique.com/>*www.nex-informatique.com
<http://www.nex-informatique.com>*
Merci de toujours citer mes messages dans vos réponses.


Le jeu. 16 févr. 2023 à 19:59, Jamie Cameron ***@***.***> a
écrit :

**Comment by iliajie** [comment] 2023-02-17 19:29
Please try to apply [this patch](https://github.com/virtualmin/virtualmin-gpl/pull/515) from a PR. It should work. Don't forget to restart Webmin afterwards!

**Comment by unsalkorkmaz** [comment] 2023-02-21 09:23
I trusted Virtualmin for 10+ years. Last week, I switch to a new server and didnt even try mails, as I said, I was trusting.
I just realized mail system was totally broken over a week.

**Comment by iliajie** [comment] 2023-02-21 10:33
> I trusted Virtualmin for 10+ years.

Thank you very much. We all appreciate your loyalty!

> I just realized mail system was totally broken over a week.

Sorry about that! We are working on fixing a new mode. Also, it is not a problem to enable the old mode, which Virtualmin worked in for the past years using `System Settings ⇾ Virtualmin Virtual Servers ⇾ Configuration: Advanced options` and setting `Create extra Unix user on Postfix systems when using user@domain format` to `Yes`. This will work for all new mail users created.

**Comment by unsalkorkmaz** [comment] 2023-02-21 10:41
I tried your fix above.. now re-checking configuration gives this error;

HTTP/1.0 500 Perl execution failed Server: MiniServ/2.013 Date: Tue, 21 Feb 2023 10:39:54 GMT Content-type: text/html; Charset=utf-8 Connection: close
ERROR — PERL EXECUTION FAILED
Undefined subroutine &virtual_server::is_dns_remote called at /usr/share/webmin/virtual-server/virtual-server-lib-funcs.pl line 14780.

![Screenshot 2023-02-21 at 13 41 32](https://user-images.githubusercontent.com/207720/220323010-c79ab393-7274-40c8-95a0-27d07dd2efc1.png)

**Comment by iliajie** [comment] 2023-02-21 10:46
You shouldn't replace the whole file. You should only change the lines that found in the PR.

**Comment by unsalkorkmaz** [comment] 2023-02-21 11:48
Forwarding is broken too.

**Comment by iliajie** [comment] 2023-02-21 16:03
> Forwarding is broken too.
> 
> correction; forwarding to Gmail is broken. Yandex working, I think. Still testing.
> 
> I remember this one; https://blog.hqcodeshop.fi/archives/122-Fixing-Googles-new-IPv6-mail-policy-with-Postfix.html#c1943
> 
> But doesnt seems working. Any solution?

What error do you get when the message is forwarded to Google?

**Comment by unsalkorkmaz** [comment] 2023-02-21 18:20
I am not good at reading these, I don't see an error;

```
Feb 21 19:11:31 ns postfix/smtpd[64125]: 47238174264E: client=mail-ua1-f48.google.com[209.85.222.48]
Feb 21 19:11:31 ns postfix/cleanup[64127]: 47238174264E: message-id=<CABZBZDsY_2Mx2QH-H1oHAN2bv7JwSHgecpc+h5gCd+JUMqrqCA@mail.gmail.com>
Feb 21 19:11:31 ns opendkim[28879]: 47238174264E: DKIM verification successful
Feb 21 19:11:31 ns opendkim[28879]: 47238174264E: s=20210112 d=gmail.com a=rsa-sha256 SSL 
Feb 21 19:11:31 ns postfix/qmgr[41792]: 47238174264E: from=<XXX@gmail.com>, size=2717, nrcpt=1 (queue active)
Feb 21 19:11:31 ns spamd[2000]: spamd: connection from ::1 [::1]:49390 to port 783, fd 5
Feb 21 19:11:31 ns spamd[2000]: spamd: setuid to bilgi@YYY.com succeeded
Feb 21 19:11:31 ns spamd[2000]: spamd: processing message <CABZBZDsY_2Mx2QH-H1oHAN2bv7JwSHgecpc+h5gCd+JUMqrqCA@mail.gmail.com> for bilgi@YYY.com:1006
Feb 21 19:11:31 ns spamd[2000]: spamd: clean message (-0.2/5.0) for bilgi@YYY.com:1006 in 0.1 seconds, 3001 bytes.
Feb 21 19:11:31 ns spamd[2000]: spamd: result: . 0 - DKIM_SIGNED,DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,FREEMAIL_FROM,HTML_MESSAGE,RCVD_IN_MSPIKE_H2,SPF_HELO_NONE,SPF_PASS scantime=0.1,size=3001,user=bilgi@YYY.com,uid=1006,required_score=5.0,rhost=::1,raddr=::1,rport=49390,mid=<CABZBZDsY_2Mx2QH-H1oHAN2bv7JwSHgecpc+h5gCd+JUMqrqCA@mail.gmail.com>,autolearn=ham autolearn_force=no
Feb 21 19:11:31 ns postfix/local[64128]: 47238174264E: to=<"bilgi@YYY.com"@SERVERNAME>, orig_to=<bilgi@YYY.com>, relay=local, delay=0.46, delays=0.17/0.01/0/0.28, dsn=2.0.0, status=sent (delivered to command: /usr/bin/procmail-wrapper -o -a $DOMAIN -d $LOGNAME)
Feb 21 19:11:31 ns postfix/cleanup[64127]: 71402174264F: message-id=<CABZBZDsY_2Mx2QH-H1oHAN2bv7JwSHgecpc+h5gCd+JUMqrqCA@mail.gmail.com>
Feb 21 19:11:31 ns postfix/local[64128]: 47238174264E: to=<"bilgi@YYY.com"@SERVERNAME>, orig_to=<bilgi@YYY.com>, relay=local, delay=0.46, delays=0.17/0.01/0/0.28, dsn=2.0.0, status=sent (forwarded as 71402174264F)
Feb 21 19:11:31 ns postfix/qmgr[41792]: 71402174264F: from=<XXX@gmail.com>, size=3061, nrcpt=1 (queue active)
Feb 21 19:11:31 ns postfix/qmgr[41792]: 47238174264E: removed
Feb 21 19:11:32 ns postfix/smtp[64149]: 71402174264F: to=<XXX@gmail.com>, orig_to=<bilgi@YYY.com>, relay=gmail-smtp-in.l.google.com[142.250.110.26]:25, delay=0.8, delays=0.28/0.01/0.16/0.34, dsn=2.0.0, status=sent (250 2.0.0 OK  1677003092 m5-20020a05600c160500b003e797b389fesi2158749wmn.23 - gsmtp)
Feb 21 19:11:32 ns postfix/qmgr[41792]: 71402174264F: removed
```

```

Feb 21 19:11:31 ns postfix/smtpd[64125]: 47238174264E: client=mail-ua1-f48.google.com[209.85.222.48]
Feb 21 19:11:31 ns postfix/cleanup[64127]: 47238174264E: message-id=<CABZBZDsY_2Mx2QH-H1oHAN2bv7JwSHgecpc+h5gCd+JUMqrqCA@mail.gmail.com>
Feb 21 19:11:31 ns opendkim[28879]: 47238174264E: DKIM verification successful
Feb 21 19:11:31 ns opendkim[28879]: 47238174264E: s=20210112 d=gmail.com a=rsa-sha256 SSL 
Feb 21 19:11:31 ns postfix/qmgr[41792]: 47238174264E: from=<XXX@gmail.com>, size=2717, nrcpt=1 (queue active)
Feb 21 19:11:31 ns spamd[2000]: spamd: connection from ::1 [::1]:49390 to port 783, fd 5
Feb 21 19:11:31 ns spamd[2000]: spamd: setuid to bilgi@YYY.com succeeded
Feb 21 19:11:31 ns spamd[2000]: spamd: processing message <CABZBZDsY_2Mx2QH-H1oHAN2bv7JwSHgecpc+h5gCd+JUMqrqCA@mail.gmail.com> for bilgi@YYY.com:1006
Feb 21 19:11:31 ns postfix/smtpd[64115]: lost connection after AUTH from unknown[46.148.40.13]
Feb 21 19:11:31 ns postfix/smtpd[64115]: disconnect from unknown[46.148.40.13] ehlo=1 auth=0/1 rset=1 commands=2/3
Feb 21 19:11:31 ns spamd[2000]: spamd: clean message (-0.2/5.0) for bilgi@YYY.com:1006 in 0.1 seconds, 3001 bytes.
Feb 21 19:11:31 ns spamd[2000]: spamd: result: . 0 - DKIM_SIGNED,DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,FREEMAIL_FROM,HTML_MESSAGE,RCVD_IN_MSPIKE_H2,SPF_HELO_NONE,SPF_PASS scantime=0.1,size=3001,user=bilgi@YYY.com,uid=1006,required_score=5.0,rhost=::1,raddr=::1,rport=49390,mid=<CABZBZDsY_2Mx2QH-H1oHAN2bv7JwSHgecpc+h5gCd+JUMqrqCA@mail.gmail.com>,autolearn=ham autolearn_force=no
Feb 21 19:11:31 ns postfix/local[64128]: 47238174264E: to=<"bilgi@YYY.com"@SERVERNAME>, orig_to=<bilgi@YYY.com>, relay=local, delay=0.46, delays=0.17/0.01/0/0.28, dsn=2.0.0, status=sent (delivered to command: /usr/bin/procmail-wrapper -o -a $DOMAIN -d $LOGNAME)
Feb 21 19:11:31 ns postfix/cleanup[64127]: 71402174264F: message-id=<CABZBZDsY_2Mx2QH-H1oHAN2bv7JwSHgecpc+h5gCd+JUMqrqCA@mail.gmail.com>
Feb 21 19:11:31 ns postfix/local[64128]: 47238174264E: to=<"bilgi@YYY.com"@SERVERNAME>, orig_to=<bilgi@YYY.com>, relay=local, delay=0.46, delays=0.17/0.01/0/0.28, dsn=2.0.0, status=sent (forwarded as 71402174264F)
Feb 21 19:11:31 ns postfix/qmgr[41792]: 71402174264F: from=<XXX@gmail.com>, size=3061, nrcpt=1 (queue active)
Feb 21 19:11:31 ns postfix/qmgr[41792]: 47238174264E: removed
Feb 21 19:11:32 ns postfix/smtp[64149]: 71402174264F: to=<XXX@gmail.com>, orig_to=<bilgi@YYY.com>, relay=gmail-smtp-in.l.google.com[142.250.110.26]:25, delay=0.8, delays=0.28/0.01/0.16/0.34, dsn=2.0.0, status=sent (250 2.0.0 OK  1677003092 m5-20020a05600c160500b003e797b389fesi2158749wmn.23 - gsmtp)
Feb 21 19:11:32 ns postfix/qmgr[41792]: 71402174264F: removed
```

**Comment by unsalkorkmaz** [comment] 2023-02-23 15:22
```

Delivered mail 63f7841636591_5af47a47186b@localhost.mail (83.4ms)
Traceback (most recent call last):
        2: from (irb):4
        1: from config/initializers/http_hostname_override.rb:27:in `post_connection_check'
OpenSSL::SSL::SSLError (hostname "mail.YYY.com" does not match the server certificate)

```

So.. if domainA is default for server SSL,
mail.domainB will not work and give SSL error, it seems.

**Comment by iliajie** [comment] 2023-02-23 15:33
> mail.domainB will not work and give SSL error, it seems.

I think we're also seeing this issue. What is the output of the following command on your system:

```
/etc/ssl/virtualmin -name ssl.* | xargs ls -lsa
```

**Comment by unsalkorkmaz** [comment] 2023-02-23 15:35
> ```
> /etc/ssl/virtualmin -name ssl.* | xargs ls -lsa
> ```
```

root@ns ~ # /etc/ssl/virtualmin -name ssl.* | xargs ls -lsa
-bash: /etc/ssl/virtualmin: Is a directory
total 556660
     4 drwx------ 11 root root      4096 Feb 22 09:05 .
     4 drwxr-xr-x 18 root root      4096 Feb 21 01:07 ..
     4 drwxr-xr-x  2 root root      4096 Feb 21 01:13 backup
     8 -rw-------  1 root root      4669 Feb 23 16:24 .bash_history
     4 -rw-r--r--  1 root root      3674 Nov 14 11:21 .bashrc
     0 -rw-r--r--  1 root root         0 Nov 14 11:21 .cloud-locale-test.skip
     4 drwxr-xr-x  2 root root      4096 Feb 21 19:49 .filemin
     4 drwxr-xr-x  5 root root      4096 Feb 12 12:52 gitlab
556292 -rw-r--r--  1 root root 569636878 Feb 21 01:14 gitlab.tar.gz
     4 drwx------  3 root root      4096 Feb 22 19:35 .gnupg
     4 drwxr-xr-x  3 root root      4096 Feb 21 01:00 .local
     4 drwx------  5 root root      4096 Feb 21 01:17 Maildir
     4 drwxr-xr-x  8 root root      4096 Feb 22 09:23 portainer_data
     4 -rw-r--r--  1 root root       161 Jul  9  2019 .profile
     4 drwxr-xr-x  2 root root      4096 Feb 21 01:13 .ssh
     4 drwxr-xr-x  2 root root      4096 Feb 23 11:59 .tmp
   304 -rw-r--r--  1 root root    304553 Feb 21 01:07 virtualmin-install.log
     4 -rw-r--r--  1 root root       165 Feb 22 09:05 .wget-hsts

```

**Comment by iliajie** [comment] 2023-02-23 15:36
Wait, sorry, I meant:

```
find /etc/ssl/virtualmin -name ssl.* | xargs ls -lsa
```

**Comment by unsalkorkmaz** [comment] 2023-02-23 15:38
> Wait, sorry, I meant:
> 
> ```
> find /etc/ssl/virtualmin -name ssl.* | xargs ls -lsa
> ```

updated

**Comment by iliajie** [comment] 2023-02-23 15:42
> So.. if domainA is default for server SSL,
> mail.domainB will not work and give SSL error, it seems.

If you visit those domains in a browser, are the SSL certificates displayed as valid?

**Comment by unsalkorkmaz** [comment] 2023-02-23 15:43
> If you visit those domains in a browser, are the SSL certificates displayed as valid?

yes. nginx server btw, not sure if its related

**Comment by iliajie** [comment] 2023-02-23 16:01
If you click on the lock icon in the browser and check for the certificate, what does it show for Common Name (CN) in Issued By section? Is it R3 or E1?

**Comment by iliajie** [comment] 2023-02-23 18:20
```
...
4 -rw------- 1 root root 1704 Feb 23 15:25 /etc/ssl/virtualmin/165494068524960/ssl.key
4 -rw------- 1 root root 1704 Feb 21 01:21 /etc/ssl/virtualmin/16549478484695/ssl.key
4 -rw------- 1 root root 1708 Feb 23 14:53 /etc/ssl/virtualmin/165494995323452/ssl.key
4 -rw------- 1 root root 1704 Feb 21 01:17 /etc/ssl/virtualmin/166548074315383/ssl.key
4 -rw------- 1 root root 1704 Feb 21 13:30 /etc/ssl/virtualmin/167697649516944/ssl.key
```

What is the out put of `find /home -name ssl.key -print -execdir openssl rsa -noout -in {} \;` then?

**Comment by unsalkorkmaz** [comment] 2023-02-23 19:46
```
root@ns ~ # find /home -name ssl.key -print -execdir openssl rsa -noout -in {} \;
/home/RANDOM/ssl.key

```

interestingly, even after I requested new Let's Encrypt cert for this one, it stays there

**Comment by iliajie** [comment] 2023-02-23 20:34
> root@ns ~ # find /home -name ssl.key -print -execdir openssl rsa -noout -in {} \;
> /home/RANDOM/ssl.key

The command should actually be:

```
find /etc/ssl/virtualmin -name ssl.key -print -execdir openssl rsa -noout -in {} \;
```

> interestingly, even after I requested new Let's Encrypt cert for this one, it stays there

What stays there?

**Comment by unsalkorkmaz** [comment] 2023-02-24 06:45
root@ns ~ # find /etc/ssl/virtualmin -name ssl.key -print -execdir openssl rsa -noout -in {} \;
```
/etc/ssl/virtualmin/167697649516944/ssl.key
/etc/ssl/virtualmin/166548074315383/ssl.key
/etc/ssl/virtualmin/165494068524960/ssl.key
/etc/ssl/virtualmin/165494995323452/ssl.key
/etc/ssl/virtualmin/16534197197637/ssl.key
/etc/ssl/virtualmin/165342006711162/ssl.key
/etc/ssl/virtualmin/16549478484695/ssl.key
/etc/ssl/virtualmin/165341871329807/ssl.key
```



> What stays there?

previous command showed 1 domain, I re-requested Let's Encrypt cert but still that command gave that 1 result.



Btw.. I can give server access to you to find this problem properly. How can I reach you privately?

**Comment by iliajie** [comment] 2023-02-24 08:44
> previous command showed 1 domain, I re-requested Let's Encrypt cert but still that command gave that 1 result.

Was this domain restored from a backup? Unless you manually changed `System Settings ⇾ Server Templates: Edit Server Template / SSL website for domain` in `Template for private key path` option from default `/etc/ssl/virtualmin/${ID}/ssl.key` to `File in home directory` all newly created domains should store SSL certificates under `/etc/ssl/virtualmin` directory.

It is better not to store domain SSL certificates under user home directory.

Besides, we have discovered and [fixed](https://github.com/webmin/webmin/commit/c3fa84a7cd9a87cf8b67e6f7994a67ef7d2fb863) yesterday a bug (on Webmin side), which created private SSL key with Let's Encrypt in the unexpected to Virtualmin format. You can try applying it and see if that works for you.

---

If it doesn't, and that issue is not related to "Autoreply mail enabled" (initial topic) then you should open a new ticket describing in short your new issue.

If the issue is realted to "Autoreply mail enabled" then it can be fixed either by applying [these patches](https://github.com/virtualmin/virtualmin-gpl/pull/515/files) from still opened PR (on Virtualmin side) or simply re-enabling creation of extra Postfix user in `System Settings ⇾ Virtualmin Virtual Servers ⇾ Configuration: Advanced options` page.

**Comment by unsalkorkmaz** [comment] 2023-02-24 12:29
> It is better not to store domain SSL certificates under user home directory.

I NEVER in my life stored in home directory but it is there, maybe because of migration.




> Besides, we have discovered and [fixed](https://github.com/webmin/webmin/commit/c3fa84a7cd9a87cf8b67e6f7994a67ef7d2fb863) yesterday a bug (on Webmin side), which created private SSL key with Let's Encrypt in the unexpected to Virtualmin format. You can try applying it and see if that works for you.

sub servers gives error;

* SSL certificate problem: unable to get local issuer certificate

**Comment by jcameron** [comment] 2023-02-24 18:33
That change to use the .combined file is actually expected - Nginx needs a single file that contains the SSL cert and the CA cert.
