### ISSUE TITLE
installation issue on debian 9.4

### ISSUE THREAD

**Issue by ahyear** [virtualmin/virtualmin-install#14] opened 2018-06-26 07:37 UTC
Hello,

As I was waiting for Ubuntu 18.04 fix, I decided to switch to debian 9.4 strech (stable) (64bits). 
I get this error:

[9/23] Configuring Net                                                  ▒▒▒▒▒▒▒Error: Unable to open /etc/network/interfaces
Error
-----
Unable to open /etc/network/interfaces
-----
▣▣▣ Cleaning up

[WARNING] The following errors occurred during installation:

  ◉ Postinstall configuration returned an error.
[WARNING] The last few lines of the log file were:
[2018/06/25 15:38:28] [INFO] - Code: 0 Result: success
[2018/06/25 15:38:28] [INFO] - Code: 0 Result: success
[2018/06/25 15:38:29] [INFO] - Code: 0 Result: success
[2018/06/25 15:38:29] [INFO] - Code: 0 Result: Warning: ZONE_ALREADY_SET: public
success
[2018/06/25 15:38:29] [INFO] - Succeeded
[2018/06/25 15:38:29] [INFO] - Configuring MySQL
[2018/06/25 15:38:34] [INFO] - Succeeded
[2018/06/25 15:38:34] [INFO] - Configuring NTP
[2018/06/25 15:38:44] [INFO] - Code: 0 Result: 25 Jun 15:38:44 ntpdate[5023]: adjust time server 2a03:4980:7:b200:ba27:ebff:fe72:7731 offset -0.000285 sec
[2018/06/25 15:38:44] [INFO] - Succeeded
[2018/06/25 15:38:44] [INFO] - Configuring Net
[2018-06-25 15:38:45 UTC] [DEBUG] Cleaning up temporary files in /tmp/.virtualmin-19611.
[2018-06-25 15:38:45 UTC] [WARNING] The following errors occurred during installation:
[2018-06-25 15:38:45 UTC] [WARNING] The last few lines of the log file were:

that the and of file

**Comment by swelljoe** [comment] 2018-07-10 19:53
Did Debian switch to netplan, too!? This is the same exact error we get on Ubuntu 18.04 systems with netplan...I haven't seen it on Debian, though. But, if they've changed the network config system, it'll be the same solution (which is ongoing).

**Comment by ahyear** [comment] 2018-08-09 12:10
ok, so what I've see is that my network conf is not in /etc/network/interfaces but in /etc/systemd/network/50-default.network 
so that is why it can't find the file. 

is the install script adapted for systemd netxork configuration?

**Comment by ahyear** [comment] 2018-08-10 06:05
I removed al sensitive informations

/etc/systemd/network/50-default.network
```
# This file sets the IP configuration of the primary (public) network device.
# You can also see this as "OSI Layer 3" config.
# It was created by the OVH installer, please be careful with modifications.
# Documentation: man systemd.network or https://www.freedesktop.org/software/systemd/man/systemd.network.html

[Match]
MACAddress=XX:XX:XX:XX:XX:XX

[Network]
Description=network interface on public network, with default route
DHCP=no
Address=XX.XX.XX.XX/xx
Gateway=XX.XX.XX.XX
#IPv6AcceptRA=false
NTP=ntp.ovh.net
DNS=127.0.0.1
DNS=XX.XX.XX.XX
DNS=XX:XX:XXXX:::1
Gateway=XXXX:XXXX:XXXX:XXXX:ff:ff:ff:ff

[Address]
Address=XXXX:XXXX:XXXX:XXXX::/64

[Route]
Destination=XXXX:XXXX:XXXX:XXXX:ff:ff:ff:ff

Scope=link
```
/etc/systemd/network/50-public-interface.link

```
# This file configures the relation between network device and device name.
# You can also see this as "OSI Layer 2" config.
# It was created by the OVH installer, please be careful with modifications.
# Documentation: man systemd.link or https://www.freedesktop.org/software/systemd/man/systemd.link.html

[Match]
MACAddress=XX:XX:XX:XX:XX:XX

[Link]
Description=network interface on public network, with default route
MACAddressPolicy=persistent
NamePolicy=kernel database onboard slot path mac
#Name=eth0	# name under which this interface is known under OVH rescue system
#Name=eno1	# name under which this interface is probably known by systemd

```

**Comment by ahyear** [comment] 2018-08-10 06:45
what i just found: https://www.virtualmin.com/node/56764

**Comment by swelljoe** [comment] 2018-08-10 20:25
Yeah, looks like yet another network configuration system. Good fun. This is gonna take a while. We still haven't quite finished netplan (Ubuntu's newfangled thing...I wish they'd gone the same route as Debian, as we now have even more things to support).

**Comment by ahyear** [comment] 2018-08-11 05:44
As it is said on the article I posted this seems to be the new standard... I will check if I see the same configuration in Ubuntu (as it is normally based on Debian )

**Comment by ahyear** [comment] 2018-08-14 09:08
I reinstalled my serveur on ubuntu 18.04 and I have the same configuration as Debian ( /etc/systemd/network) so I guess it is not a netplan configuration that has to be adapted but a systemd one.

**Comment by acosonic** [comment] 2019-07-23 11:13
I can confirm that issue is still not fixed... Netplan comes by default, and on cloud VPS, it configures networking automatically, it's a real trouble to change it, especially with IPv6

**Comment by rostovtsev** [comment] 2019-07-23 11:19
What Webmin version is getting installed?

**Comment by acosonic** [comment] 2019-07-23 11:23
I've done `apt update & apt upgrade` (nothing to install), then installed from

`wget http://software.virtualmin.com/gpl/scripts/install.sh`

**Comment by rostovtsev** [comment] 2019-07-23 12:21
Is Webmin version installed 1.900?  Version 1.920 has `netplan` fixes.

**Comment by acosonic** [comment] 2019-07-23 12:51
/archives/webmin_1.920_all.deb ...
Unpacking webmin (1.920) ...

**Comment by acosonic** [comment] 2019-07-23 12:55
I've added 
deb http://download.webmin.com/download/repository sarge contrib

manually, howver, seems that
wget http://software.virtualmin.com/gpl/scripts/install.sh

Doesn't add it to the sources list, but it rather adds some old repo, which doesn't work...

**Comment by acosonic** [comment] 2019-07-23 12:56
Also uninstalling (from the above repo, doesn't work, which is probably a different issue...

```
apt remove webmin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apt-show-versions libapt-pkg-perl libauthen-pam-perl libio-pty-perl libnet-ssleay-perl libpython-stdlib libpython2.7-minimal libpython2.7-stdlib perl-openssl-defaults
  python python-minimal python2.7 python2.7-minimal
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  webmin
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 175 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 92873 files and directories currently installed.)
Removing webmin (1.920) ...
Running uninstall scripts ..
Can't locate WebminCore.pm in @INC (you may need to install the WebminCore module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/webmin/run-uninstalls.pl line 6.
BEGIN failed--compilation aborted at /usr/share/webmin/run-uninstalls.pl line 6.

```

**Comment by acosonic** [comment] 2019-07-23 13:18
Yes, the script at
http://software.virtualmin.com/gpl/scripts/install.sh

Adds following repos:
```
deb http://software.virtualmin.com/vm/6/gpl/apt virtualmin-bionic main
deb http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal main

```
Instead of:
deb http://download.webmin.com/download/repository sarge contrib

and installed webmin is: 1.900

**Comment by swelljoe** [comment] 2023-02-14 19:15
Closing this as no longer relevant, since the Virtualmin 7 installer has been released, and Debian 9 reached EOL. I think we install OK on Debian 10 and 11, and I think we safely handle the newer network config system (I don't know if it's fully supported, but I'm pretty sure we don't break it).

**Closed by swelljoe** 2023-02-14 19:15 UTC
